// containers/Article.vue
<style src="./Article.css" lang="postcss" module></style>

<template>
  <div :class="$style.base">
    <ArticleHeader :title="page.title" :src="page.thumbnail" :blur="true" />
    <div :class="$style.content">
      <SocialButtonList :title="page.title" />
      <MarkdownContent :ast="page.content" />
    </div>
  </div>
</template>

<script>
import generateHead from '~/utils/generateHead';
import fetchData from '~/utils/fetchData';
import ArticleHeader from '~/components/ArticleHeader';
import SocialButtonList from '~/components/SocialButtonList';
import MarkdownContent from '~/components/MarkdownContent';

export default {
  head: generateHead,
  asyncData: fetchData,
  components: {
    ArticleHeader,
    SocialButtonList,
    MarkdownContent,
  },
};
</script>

// src/containers/Article.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './Article.css';
import withTracker from '~/lib/withTracker';
import withMetadata from '~/lib/withMetadata';
import withRouteData from '~/lib/withRouteData';
import ArticleHeader from '~/components/ArticleHeader';
import SocialButtonList from '~/components/SocialButtonList';
import MarkdownContent from '~/components/MarkdownContent';

const Article = ({ page }) => (
  <div className={styles.base}>
    <ArticleHeader title={page.title} src={page.thumbnail} blur={true} />
    <div className={styles.content}>
      {!page.preview && <SocialButtonList title={page.title} />}
      <MarkdownContent ast={page.content} />
    </div>
  </div>
);

const ArticleWithStyles = withStyles(styles)(Article);

export { ArticleWithStyles as Article };
export default withTracker(withMetadata(withRouteData(ArticleWithStyles)));
