// src/components/CardList.jsx
import React from 'react';
import classnames from 'classnames';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './CardList.css';

const CardList = ({ wrap, children }) => (
  <div className={styles.base}>
    <div className={styles.outer}>
      <div
        className={classnames({
          [styles.inner]: true,
          [styles.innerWrap]: wrap,
        })}
      >
        {children}
      </div>
    </div>
  </div>
);

export default withStyles(styles)(CardList);

// components/CardList.vue
<style src="./CardList.css" lang="postcss" module></style>

<template>
  <div :class="$style.base">
    <div :class="$style.outer">
      <div
        :class="{
          [$style.inner]: true,
          [$style.innerWrap]: wrap,
        }"
      >
        <slot/>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    wrap: { type: Boolean, default: false },
    itemsLength: { type: Number, required: true },
  },
};
</script>
