// src/components/ItemCard.jsx
import React from 'react';
import classnames from 'classnames';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './ItemCard.css';

const ItemCard = ({ wide, children }) => (
  <div
    className={classnames({
      [styles.itemWrapper]: true,
      [styles.wide]: wide,
    })}
  >
    <div className={styles.item}>{children}</div>
  </div>
);

export default withStyles(styles)(ItemCard);

// components/ItemCard.vue
<style src="./ItemCard.css" lang="postcss" module></style>

<template>
  <div :class="{
    [$style.itemWrapper]: true,
    [$style.wide]: wide,
  }">
    <div :class="$style.item">
      <slot />
    </div>
  </div>
</template>

<script>
export default {
  props: {
    wide: {
      type: Boolean,
      default: false,
    },
  },
};
</script>
