// src/components/ReadmoreCard.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';

import styles from './ReadmoreCard.css';
import ItemCard from '~/components/ItemCard';
import Link from '~/components/Link';
import FontAwesome from '~/components/FontAwesome';

const ReadmoreCard = ({ wide, href }) => (
  <ItemCard wide={wide}>
    <Link className={styles.base} href={href}>
      <div>
        <FontAwesome className={styles.iconCircle} name="arrow-right" />
      </div>
      <div className={styles.textWrapper}>
        <span className={styles.text}>
          <strong>もっと見る</strong>
        </span>
      </div>
    </Link>
  </ItemCard>
);

export default withStyles(styles)(ReadmoreCard);

// components/ReadmoreCard.vue
<style src="./ReadmoreCard.css" lang="postcss" module></style>

<template>
  <ItemCard :wide="wide">
    <Link :class="$style.base" :href="href">
      <div>
        <FontAwesome :class="$style.iconCircle" name="arrow-right" />
      </div>
      <div :class="$style.textWrapper">
        <span :class="$style.text">
          <strong>もっと見る</strong>
        </span>
      </div>
    </Link>
  </ItemCard>
</template>

<script>
import ItemCard from './ItemCard';

export default {
  props: {
    href: {
      type: String,
      required: true,
    },
    wide: {
      type: Boolean,
      default: false,
    },
  },
  components: {
    ItemCard,
  },
};
</script>
