// src/components/SectionHeader.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './SectionHeader.css';
import Link from '~/components/Link';

const SectionHeader = ({ children, href }) => (
  <header className={styles.base}>
    <h2 className={styles.header}>
      {href ? (
        <Link href={href} className={styles.link}>
          <span className={styles.headerInner}>{children}</span>
        </Link>
      ) : (
        <span className={styles.headerInner}>{children}</span>
      )}
    </h2>
  </header>
);

export default withStyles(styles)(SectionHeader);

// components/SectionHeader.vue
<style src="./SectionHeader.css" lang="postcss" module></style>

<template>
  <header :class="$style.base">
    <h2 :class="$style.header">
      <span :class="$style.headerInner">
        <slot />
      </span>
      <Link v-if="href" :class="$style.moreLink" :href="href">
        <span>もっと見る</span>
        <FontAwesome name="angle-right" />
      </Link>
    </h2>
  </header>
</template>

<script>
export default {
  props: ['href'],
};
</script>
