// src/components/SocialButton.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './SocialButton.css';
import Link from '~/components/Link';
import FontAwesome from '~/components/FontAwesome';

const SocialButton = ({ href, color, icon, text }) => (
  <div className={styles.base}>
    <Link className={styles.button} href={href} style={{ backgroundColor: color }}>
      <FontAwesome className={styles.icon} name={icon} />
      <span>{text}</span>
    </Link>
  </div>
);

export default withStyles(styles)(SocialButton);

// components/SocialButton.vue
<style src="./SocialButton.css" lang="postcss" module></style>

<template>
  <div :class="$style.base">
    <Link :class="$style.button" :href="href" :style="{ backgroundColor: color }">
      <FontAwesome :class="$style.icon" :name="icon" />
      <span>{{text}}</span>
    </Link>
  </div>
</template>

<script>
export default {
  props: {
    href: {
      type: String,
      required: true,
    },
    color: {
      type: String,
      required: true,
    },
    text: {
      type: String,
      required: true,
    },
    icon: {
      type: String,
      required: true,
    },
  },
};
</script>
