// src/components/SocialButtonList.jsx
import React from 'react';
import { withSiteData, withRouteData } from 'react-static';
import url from 'url';
import encodeUrl from 'encodeurl';

import styles from './SocialButtonList.css';
import SocialButton from '~/components/SocialButton';
import { withRouter } from 'react-router';
import withStyles from 'isomorphic-style-loader/lib/withStyles';

const Utils = {
  getPageUrl(baseUrl, path) {
    return encodeUrl(url.resolve(baseUrl, path));
  },
  getPageTitle(siteTitle, title) {
    return `${title} | ${process.env.siteTitle}`;
  },
  getTwitterUrl(title, url) {
    const pageTitle = encodeURIComponent(title);
    const pageUrl = encodeURIComponent(url);
    return `https://twitter.com/intent/tweet?url=${pageUrl}&text=${pageTitle}`;
  },
  getFacebookUrl(url) {
    const pageUrl = encodeURIComponent(url);
    return `https://www.facebook.com/sharer/sharer.php?u=${pageUrl}`;
  },
};

const SocialButtonList = ({ site, page, location }) => {
  const pageTitle = Utils.getPageTitle(site.title, page.title);
  const pageUrl = Utils.getPageUrl(site.root, location.pathname);

  return (
    <div className={styles.base}>
      <SocialButton
        href={Utils.getTwitterUrl(pageTitle, pageUrl)}
        color="#1DA1F2"
        text="Tweet"
        icon="twitter"
      />
      <SocialButton
        href={Utils.getFacebookUrl(pageUrl)}
        color="#3B5998"
        text="Share"
        icon="facebook-official"
      />
    </div>
  );
};

export default withSiteData(withRouteData(withRouter(withStyles(styles)(SocialButtonList))));

// components/SocialButtonList.vue
<style src="./SocialButtonList.css" lang="postcss" module></style>

<template>
  <div :class="$style.base">
    <SocialButton :href="twitterUrl" color="#1DA1F2" text="Tweet" icon="twitter" />
    <SocialButton
      :href="facebookUrl"
      color="#3B5998"
      text="Share"
      icon="facebook-official"
    />
  </div>
</template>

<script>
import url from 'url';
import encodeUrl from 'encodeurl';
import SocialButton from './SocialButton';

export default {
  props: {
    title: {
      type: String,
      required: true,
    },
  },
  computed: {
    pageUrl() {
      return encodeUrl(url.resolve(process.env.baseUrl, this.$route.path));
    },
    pageTitle() {
      return `${this.title} | ${process.env.siteTitle}`;
    },
    twitterUrl() {
      const pageTitle = encodeURIComponent(this.pageTitle);
      const pageUrl = encodeURIComponent(this.pageUrl);
      return `https://twitter.com/intent/tweet?url=${pageUrl}&text=${pageTitle}`;
    },
    facebookUrl() {
      const pageTitle = encodeURIComponent(this.pageTitle);
      const pageUrl = encodeURIComponent(this.pageUrl);
      return `https://www.facebook.com/sharer/sharer.php?u=${pageUrl}`;
    },
  },
  components: {
    SocialButton,
  },
};
</script>
