// components/AutoTextWrap.vue
<style src="./AutoTextWrap.css" lang="postcss" module></style>

<template>
  <span>
    <template v-for="(word, idx) in words">
      <span :key="idx" role="presentation" :class="$style.word">{{word}}</span>
    </template>
  </span>
</template>

<script>
import Mikan from 'mikanjs';

export default {
  props: {
    text: {
      type: String,
      required: true,
    },
  },
  computed: {
    words() {
      return Mikan.split(this.text);
    },
  },
};
</script>

// src/components/AutoTextWrap.jsx
import React from 'react';
import Mikan from 'mikanjs';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './AutoTextWrap.css';

const AutoTextWrap = ({ text }) => {
  if (!text) {
    return <span />;
  }
  const words = Mikan.split(text);
  return (
    <span>
      {words.map((word, idx) => (
        <span key={idx} role="presentation" className={styles.word}>
          {word}
        </span>
      ))}
    </span>
  );
};

export default withStyles(styles)(AutoTextWrap);
