// components/FaceImage.vue
<style src="./FaceImage.css" lang="postcss" module></style>

<template>
  <div :class="$style.base" :style="{ width: size && `${size}px`, height: size && `${size}px` }">
    <div :class="$style.imagePadding" />
    <OptimizedImage :class="$style.image" :src="src" :width="size" :height="size" />
  </div>
</template>

<script>
export default {
  props: {
    src: {
      type: String,
      required: true,
    },
    size: {
      type: [String, Number],
    },
  },
};
</script>

// src/components/FaceImage.jsx
import React from 'react';

import styles from './FaceImage.css';
import OptimizedImage from '~/components/OptimizedImage';
import withStyles from 'isomorphic-style-loader/withStyles';

const FaceImage = ({ src, size }) => (
  <div className={styles.base} style={{ width: size && `${size}px`, height: size && `${size}px` }}>
    <div className={styles.imagePadding} />
    <OptimizedImage className={styles.image} src={src} width={size} height={size} />
  </div>
);

export default withStyles(styles)(FaceImage);
