// components/MarkdownContent.vue
<style src="./MarkdownContent.css" lang="postcss" module></style>

<script>
import toH from 'hast-to-hyperscript';
import AwesomeIframe from './AwesomeIframe';

export default {
  data: () => ({
    components: {
      a: 'Link',
      img: 'MarkdownImage',
      iframe: 'AwesomeIframe',
    },
  }),
  props: {
    ast: {
      type: Object,
      required: true,
    },
  },
  render(h) {
    const _h = (tag, attrs, children) => {
      const _tag = this.components[tag] || tag;
      return h(_tag, { attrs }, children);
    };
    return h('div', { class: this.$style.markdownBody }, [toH(_h, this.ast)]);
  },
  components: {
    AwesomeIframe,
    MarkdownImage: {
      props: ['src'],
      render(h) {
        return h('OptimizedImage', {
          attrs: {
            width: 500,
            src: this.src,
          },
        });
      },
    },
  },
};
</script>

// src/components/MarkdownContent.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/withStyles';
import unified from 'unified';
import rehypeReact from 'rehype-react';

import styles from './MarkdownContent.css';
import Link from '~/components/Link';
import AwesomeIframe from '~/components/AwesomeIframe';
import OptimizedImage from '~/components/OptimizedImage';

const processor = unified()
  .use(rehypeReact, {
    createElement: React.createElement,
    components: {
      a: Link,
      iframe: AwesomeIframe,
      img: function MarkdownImage(props) {
        return <OptimizedImage {...props} width={500} />;
      },
    },
  })
  .freeze();

const MarkdownContent = ({ ast }) => (
  <div className={styles.markdownBody}>{processor.stringify(ast)}</div>
);
MarkdownContent.defaultProps = {
  ast: {
    type: 'element',
    tagName: 'div',
    properties: {},
    children: [],
  },
};

export default withStyles(styles)(MarkdownContent);
