// components/MemberCard.vue
<style src="./MemberCard.css" lang="postcss" module></style>

<template>
  <div :class="$style.base">
    <Link :href="info.permalink">
      <div :class="$style.image">
        <FaceImage :src="info.avatar" />
      </div>
      <div :class="$style.description">
        <p :class="$style.descriptionLine">
          <small :class="$style.status">{{status}}</small>
        </p>
        <p :class="$style.descriptionLine">
          <span :class="$style.name">
            <span>{{info.title}}</span>
            <FontAwesome name="angle-right" />
          </span>
        </p>
      </div>
    </Link>
  </div>
</template>

<script>
import FaceImage from './FaceImage';

export default {
  props: {
    info: {
      type: Object,
      required: true,
    },
  },
  computed: {
    status() {
      const info = this.info;
      return info.category === '99_OB'
        ? `${info.year_of_graduation}年度卒業`
        : `${info.category.split('_')[1]}${info.school_year || ''}`;
    },
  },
  components: {
    FaceImage,
  },
};
</script>

// src/components/MemberCard.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/withStyles';

import styles from './MemberCard.css';
import FaceImage from '~/components/FaceImage';
import Link from '~/components/Link';
import FontAwesome from '~/components/FontAwesome';

const MemberCard = ({ info }) => {
  const status =
    info.category === '99_OB'
      ? `${info.year_of_graduation}年度卒業`
      : `${info.category.split('_')[1]}${info.school_year || ''}`;

  return (
    <div className={styles.base}>
      <Link href={info.permalink}>
        <div className={styles.image}>
          <FaceImage src={info.avatar} />
        </div>
        <div className={styles.description}>
          <p className={styles.descriptionLine}>
            <small className={styles.status}>{status}</small>
          </p>
          <p className={styles.descriptionLine}>
            <span className={styles.name}>
              <span>{info.title}</span>
              <FontAwesome name="angle-right" />
            </span>
          </p>
        </div>
      </Link>
    </div>
  );
};

export default withStyles(styles)(MemberCard);
