// components/Pagination.vue
<style lang="postcss" module>
@import '~/styles/variables.css';

.base {
  display: flex;
  padding-top: 1rem;
  justify-content: center;
}

.wrapper {
  display: inline-flex;
  max-width: 100%;
  justify-content: center;
  flex-wrap: nowrap;
  list-style-type: none;
  box-shadow: 0 2px 5px 0 color(var(--black) alpha(0.25));
}

.link-wrapper {
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 3em;
  flex: 0 1 auto;
}

.link {
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  flex: 0 1 auto;
  height: 2em;
}

.enabled {
  color: var(--cyan);
  background-color: transparent;

  &:hover {
    color: var(--white);
    background-color: color(var(--cyan) alpha(0.75));
  }
}

.disabled {
  color: color(var(--black) alpha(0.25));

  &:hover {
    color: color(var(--black) alpha(0.25));
  }
}

.current {
  background-color: var(--cyan);
  color: var(--white);

  &:hover {
    color: var(--white);
  }
}
</style>

<template>
  <div :class="$style.base">
    <ul :class="$style.wrapper">
      <li v-if="isShownPrevDots" :class="$style.linkWrapper">
        <span :class="[$style.link, $style.disabled]">...</span>
      </li>
      <template v-for="cnt in pagination">
        <li :key="cnt" :class="$style.linkWrapper">
          <Link v-if="cnt !== current" :class="[$style.link, $style.enabled]" :href="generatePath(cnt)">{{cnt}}</Link>
          <span v-else :class="[$style.link, $style.current]">{{cnt}}</span>
        </li>
      </template>
      <li v-if="isShownNextDots" :class="$style.linkWrapper">
        <span :class="[$style.link, $style.disabled]">...</span>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  props: {
    current: {
      type: Number,
      required: true,
    },
    maxCount: {
      type: Number,
      required: true,
    },
    basePath: {
      type: String,
      required: true,
    },
  },
  computed: {
    pagination() {
      const startShowCount = Math.max(this.current - 2, 1);
      const lastShowCount = Math.min(this.current + 2, this.maxCount);
      const pagenation = [];
      for (let cnt = startShowCount; cnt <= lastShowCount; cnt++) {
        pagenation.push(cnt);
      }
      return pagenation;
    },
    isShownPrevDots() {
      return this.current - 2 > 1;
    },
    isShownNextDots() {
      return this.current + 2 < this.maxCount;
    },
  },
  methods: {
    generatePath(cnt) {
      if (cnt <= 1) {
        return this.basePath;
      }
      return `${this.basePath}page/${cnt}/`;
    },
  },
};
</script>

// src/components/Pagination.jsx
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import classnames from 'classnames';

import styles from './Pagination.css';
import Link from '~/components/Link';

class Pagination extends React.Component {
  get isShownPrevDots() {
    return this.props.current - 2 > 1;
  }

  get isShownNextDots() {
    return this.props.current + 2 < this.props.maxCount;
  }

  getPagination = () => {
    const { current, maxCount } = this.props;
    const startCount = Math.max(current - 2, 1);
    const lastCount = Math.min(current + 2, maxCount);

    const pagination = [];
    for (let cnt = startCount; cnt <= lastCount; cnt++) {
      pagination.push(
        <li key={cnt} className={styles.linkWrapper}>
          {this.generateLink(cnt)}
        </li>,
      );
    }
    return pagination;
  };

  generateLink = pageNum => {
    const { current } = this.props;
    if (pageNum !== current) {
      return (
        <Link
          className={classnames([styles.link, styles.enabled])}
          href={this.generatePath(pageNum)}
        >
          {pageNum}
        </Link>
      );
    } else {
      return <span className={classnames([styles.link, styles.current])}>{pageNum}</span>;
    }
  };

  generatePath = cnt => {
    if (cnt <= 1) {
      return this.props.basePath;
    }
    return `${this.props.basePath}page/${cnt}/`;
  };

  render() {
    const dots = (
      <li className={styles.linkWrapper}>
        <span className={classnames([styles.link, styles.disabled])}>{'...'}</span>
      </li>
    );

    return (
      <div className={styles.base}>
        <ul className={styles.wrapper}>
          {this.isShownPrevDots && dots}
          {this.getPagination()}
          {this.isShownNextDots && dots}
        </ul>
      </div>
    );
  }
}

export default withStyles(styles)(Pagination);
